---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: devops-rs
spec:
  replicas: 3
  selector:
     matchLabels:
         app: swiggy
     template:
      metadata:
        labels:
           app: swiggy
      spec:
        containers:
           - name: con-1
             image: shaikmustafa/dm
             ports:
             - containerPort: 80
